// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import ResponsiveNav from "@/components/Navbar/ResponsiveNav";
import Footer from "@/components/Footer/Footer";
import { CartProvider } from "@/context/CartContext"; // ✅ Import CartProvider

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider> {/* ✅ Wrap everything inside CartProvider */}
          <ResponsiveNav />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
