// import Footer from "@/components/Footer/Footer";
import ResponsiveNav from "@/components/Navbar/ResponsiveNav";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import ClientProvider from "@/components/Provinder/Provinder";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          <ResponsiveNav />
          {children}
          <ToastContainer />
          {/* <Footer /> */}
        </ClientProvider>
      </body>
    </html>
  );
}
